### ISSUE TITLE
Unable to Convert tokens after Approve transaction successfully mined

### ISSUE THREAD

**Issue by ltfschoen** [rsksmart/tokenbridge#181]
If after your Approve transaction is successfully mined you accidently click the 'Approve' button a second time and then reject the second transaction, then all the buttons in the UI will be disabled even if you connect your account again with Metamask

It happened to me, I went to https://tokenbridge.rsk.co/, then chose an amount of USDT, and submitted the transaction by clicking Approve, choosing gas fee, and submitting it, and then when I went to the transaction hash on Etherscan it showed it was successfully mined with message  "ApprovedUSDTFor Trade On 0x12ed69359919fc775bc2674860e8fe2d2b6a7b5d"

But I accidently clicked the "Approve" button a second time, even though the approval had already been mined successfully, so i just rejected that 2nd transaction since it'd already been approved.

But then even after i connected my wallet with Metamask again, both the "Approve" and "Convert tokens" button are both disabled, so it didn't seem possible to do the next step of "Convert tokens".

And it said "No transactions for active account found", even though that account had a successful transaction that cost US$12 to approve spending the funds.

So I couldn't even try clicking "Approve" a 3rd time as that was disabled too

I got around the issue by just changing the code in the browser

I just went to "inspect element", found the "Convert tokens" button, and removed the `disabled` text from this html element `<button id="deposit" type="submit" class="btn btn-primary ml-3 mt-3 mb-3" disabled="">Convert tokens</button>`, then it wasn't disabled anymore, so i could just click it and Metamask popped up and allowed me to convert my USDT to rUSDT, and tx was successful.

**Comment by pmprete** [comment]
Thanks @ltfschoen for openning this issue, we will try to fix it as soon as we can

**Comment by pmprete** [comment]
We deployed fixed of the typos and the USDT approve issue, thanks for reporting this
