### ISSUE TITLE
Error: connection not open on send()

### ISSUE THREAD

**Issue by jacobabiola** [rsksmart/tokenbridge#207]
Hello Rskstars,

Thank you guys for sharing your talent with the world. I am experimenting with the tokenbridge codebase, I was able to deploy the contracts and setup the necessary config, i am stuck at this error when running the federator script

So I tried to run the Federator server and I get this error on the terminal.

Error: connection not open on send()

See the attached screenshot

![error](https://user-images.githubusercontent.com/24619534/118293029-22cda880-b4d1-11eb-93a9-f60b0426b0a1.JPG)

**Comment by pmprete** [comment]
Hi Jacobabiola, it seems like that web3 is saying that there is an issue with your connection. Check the host used in the config files, try to use curl to see if you get a response to see if it's the correct url and there is no firewall blocking it.

**Comment by jacobabiola** [comment]
Hi @pmprete , you were right Afterall, this was what I set for host : "https://kovan.infura.io/v3/e9061398f8f24b1f823f438c8066a03c". I guess I don't know the right format, please what should the host look like?

**Comment by pmprete** [comment]
That url looks ok, i thought you where using the wss:// one.
Remember that the bridge has 2 connections in config.js it may be the other one that is not correct, check that url as well.
Also remember that you can set ip blocks or need an authentication acording to your infura configuration, make sure you can call the endpoint using curl to discard connection issues.

**Comment by pmprete** [comment]
That url looks ok, i thought you where using the wss:// one.
Remember that the bridge has 2 connections in config.js it may be the other one that is not correct, check that url as well.
Also remember that you can set ip blocks or need an authentication according to your infura configuration, make sure you can call the endpoint using curl to discard connection issues.

**Comment by jacobabiola** [comment]
thank you so much it worked.
