### ISSUE TITLE
Host address

### ISSUE THREAD

**Issue by calibre24** [rsksmart/tokenbridge#208]
Hi Guys,

Please which this the proper format of address for the HOST ? i entered my infura url it seems not to work.
i need a sample host address
{
    "bridge": "0x684a8a976635fb7ad74a0134ace990a6a0fcce84",
    "federation": "0x36c893a955399cf15a4a2fbef04c0e06d4d9b379",
    "testToken": "0x5d248f520b023acb815edecd5000b98ef84cbf1b",
    "multisig": "0x88f6b2bc66f4c31a3669b9b1359524abf79cfc4a",
    "allowTokens": "0x952b706a9ab5fd2d3b36205648ed7852676afbe7",
    "host": "<YOUR HOST URL AND PORT>",
    "fromBlock": 434075
}

**Comment by pmprete** [comment]
Infura url should work, it should look like this: 
`https://kovan.infura.io/v3/<YOUR PROJECT ID>`
remember that url is different from kovan, rinkeby, rosptain and mainnet

**Comment by pmprete** [comment]
Closed for inactivity
