### ISSUE TITLE
Incorrect Network

### ISSUE THREAD

**Issue by jacobabiola** [rsksmart/tokenbridge#209]
I was setting up the frontend to work with my testnet deployment.  even though i changed the neccessary configs to testnet i still get the attached error message. 

what could be doing wrong?

![network](https://user-images.githubusercontent.com/24619534/118507957-a3d1ad80-b726-11eb-9a96-c38cd430b1b7.JPG)

**Comment by pmprete** [comment]
The testnet configs are used if the url includes testnet or if you pass it as an argument.
Try this url in chrome
http://localhost:7000?testnet=true

**Comment by jacobabiola** [comment]
Awesome!!. its worked.  Thank you so much :)
